tryToComeIn mode error
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  org.simpleframework.xml.core.AttributeException: Attribute 'tryToComeInMode' does not have a match in class org.volante.abm.example.GiveUpGiveInAllocationModel at line 4